LuxAI_S2-v0-sSqunet-78env-deimos-lr2-no-guide:
  &lux-ssqunet-78envs-deimos-lr2-no-guide
  additional_keys_to_log:
    - stats
    - results
  algo_hyperparams: &lux-ssqunet-78envs-deimos-lr2-no-guide-algo
    autocast_loss: true
    num_minibatches: 6
    ent_coef: 0.01
    gae_lambda:
      - 0.95
      - 0.95
      - 0.95
    gamma:
      - 1
      - 1
      - 1
    gradient_accumulation: true
    learning_rate: !!float 1e-4
    max_grad_norm: 0.5
    multi_reward_weights:
      - 0.25
      - 0.65
      - 0.1
    normalize_advantage: false
    scale_loss_by_num_actions: true
    vf_coef:
      - 0.2
      - 0.2
      - 0.2
  device_hyperparams:
    set_float32_matmul_precision: high
  env_hyperparams: &lux-ssqunet-78envs-deimos-lr2-no-guide-env
    additional_win_loss_reward: true
    additional_win_loss_smoothing_factor: 0.9
    env_type: lux
    make_kwargs: &lux-ssqunet-78envs-deimos-lr2-no-guide-env-make-kwargs
      bid_std_dev: 0
      factory_ice_distance_buffer: null
      reward_weights:
        built_heavy_by_time_remaining: 0.11
        built_light_by_time_remaining: 0.009
    n_envs: 78
    score_reward_kwargs:
      episode_end: true
    self_play_kwargs:
      first_window_orig_policy: true
      num_old_policies: 24
      save_steps: 1000000.0
      swap_steps: 3000
      swap_window_size: 6
      window: 50
    vec_env_class: ray
  env_id: LuxAI_S2-v0
  checkpoints_kwargs:
    history_size: 1
  eval_hyperparams: &lux-ssqunet-78envs-deimos-lr2-no-guide-eval
    deterministic: false
    env_overrides: &lux-ssqunet-78envs-deimos-lr2-no-guide-eval-env-overrides
      additional_win_loss_reward: false
      make_kwargs: &lux-ssqunet-78envs-deimos-lr2-no-guide-eval-env-make-kwargs
        bid_std_dev: 0
        factory_ice_distance_buffer: null
        reward_weights:
          win_loss: 1
      n_envs: 64
      score_reward_kwargs: null
      self_play_kwargs: null
      play_checkpoints_kwargs:
        n_envs_against_checkpoints: null
    only_checkpoint_initial_policy: true
    only_record_video_on_best: true
    score_function: mean
    score_threshold: null
    step_freq: 5000000.0
  hyperparam_transitions_kwargs:
    &lux-ssqunet-78envs-deimos-lr2-no-guide-hparam-transitions
    durations:
      - 0
      - 0.1
      - 0.55
      - 0.3
      - 0.05
    interpolate_method: cosine
    phases:
      - ent_coef: 0.001
        learning_rate: 1.0e-06
      - ent_coef: 0.001
        learning_rate: 2.0e-05
      - ent_coef: 0.0001
        learning_rate: 1.0e-06
  n_timesteps: 50000000.0
  policy_hyperparams: &lux-ssqunet-78envs-deimos-lr2-no-guide-policy
    actor_head_style: squeeze_unet
    additional_critic_activation_functions:
      - tanh
      - tanh
    channels_per_level:
      - 128
      - 128
      - 128
    critic_shares_backbone: true
    decoder_residual_blocks_per_level:
      - 2
      - 2
    deconv_strides_per_level:
      - - 2
        - 2
      - - 2
        - 2
    encoder_residual_blocks_per_level:
      - 2
      - 2
      - 4
    load_run_path: sgoodfriend/rl-algo-impls-lux-nips1/act6rrp0
    output_activation_fn: identity
    save_critic_separate: false
    strides_per_level:
      - 4
      - 4
    subaction_mask:
      1:
        2: 0
        3: 1
        4: 1
        5: 2
  rollout_hyperparams: &lux-ssqunet-78envs-deimos-lr2-no-guide-rollout
    full_batch_off_accelerator: true
    n_steps: 64
    num_envs_reset_every_rollout: 12
  rollout_type: sync

LuxAI_S2-v0-sSqunet-78env-deimos-lr2-high_vf:
  &lux-ssqunet-78envs-deimos-lr2-high-vf
  <<: *lux-ssqunet-78envs-deimos-lr2-no-guide
  algo_hyperparams:
    <<: *lux-ssqunet-78envs-deimos-lr2-no-guide-algo
    vf_coef: [0.3, 0.3, 0.3]

LuxAI_S2-v0-sSqunet-78env-deimos-lr1-no-guide:
  &lux-ssqunet-78envs-deimos-lr1-no-guide
  <<: *lux-ssqunet-78envs-deimos-lr2-no-guide
  hyperparam_transitions_kwargs:
    interpolate_method: cosine
    phases:
      - learning_rate: !!float 1e-6
        ent_coef: 0.001
      - learning_rate: !!float 1e-5
        ent_coef: 0.001
      - learning_rate: !!float 1e-6
        ent_coef: 0.0001
    durations:
      - 0
      - 0.1
      - 0.55
      - 0.3
      - 0.05

LuxAI_S2-v0-sSqunet-78env-deimos-lr1-high_vf:
  &lux-ssqunet-78envs-deimos-lr1-high-vf
  <<: *lux-ssqunet-78envs-deimos-lr1-no-guide
  algo_hyperparams: &lux-ssqunet-78envs-deimos-lr1-high-vf-algo
    <<: *lux-ssqunet-78envs-deimos-lr2-no-guide-algo
    vf_coef: [0.3, 0.3, 0.3]

LuxAI_S2-v0-sSqunet-78env-deimos-lr1-adv-norm:
  &lux-ssqunet-78envs-deimos-lr1-adv-norm
  <<: *lux-ssqunet-78envs-deimos-lr1-high-vf
  algo_hyperparams: &lux-ssqunet-78envs-deimos-lr1-adv-norm-algo
    <<: *lux-ssqunet-78envs-deimos-lr1-high-vf-algo
    normalize_advantage: true

LuxAI_S2-v0-sSqunet-78env-deimos-lr2-adv-norm:
  &lux-ssqunet-78envs-deimos-lr2-adv-norm
  <<: *lux-ssqunet-78envs-deimos-lr1-adv-norm
  hyperparam_transitions_kwargs:
    <<: *lux-ssqunet-78envs-deimos-lr2-no-guide-hparam-transitions

LuxAI_S2-v0-sSqunet-78env-deimos-lrH-adv-norm:
  &lux-ssqunet-78envs-deimos-lrh-adv-norm
  <<: *lux-ssqunet-78envs-deimos-lr2-adv-norm
  hyperparam_transitions_kwargs:
    interpolate_method: cosine
    phases:
      - learning_rate: !!float 1e-6
        ent_coef: 0.001
      - learning_rate: !!float 5e-6
        ent_coef: 0.001
      - learning_rate: !!float 1e-6
        ent_coef: 0.0001
    durations:
      - 0
      - 0.2
      - 0.5
      - 0.25
      - 0.05

LuxAI_S2-v0-sSqunet-78env-deimos-lr4-no-guide:
  &lux-ssqunet-78envs-deimos-lr4-no-guide
  <<: *lux-ssqunet-78envs-deimos-lr2-no-guide
  hyperparam_transitions_kwargs:
    &lux-ssqunet-78envs-deimos-lr4-no-guide-hparam-transitions
    interpolate_method: cosine
    phases:
      - learning_rate: !!float 1e-6
        ent_coef: 0.001
      - learning_rate: !!float 4e-5
        ent_coef: 0.001
      - learning_rate: !!float 1e-6
        ent_coef: 0.0001
    durations:
      - 0
      - 0.1
      - 0.55
      - 0.3
      - 0.05

LuxAI_S2-v0-sSqunet-78env-deimos-lr4-adv-norm:
  &lux-ssqunet-78envs-deimos-lr4-adv-norm
  <<: *lux-ssqunet-78envs-deimos-lr2-adv-norm
  hyperparam_transitions_kwargs:
    <<: *lux-ssqunet-78envs-deimos-lr4-no-guide-hparam-transitions

LuxAI_S2-v0-sSqunet-78env-deimos-lr16-no-guide:
  &lux-ssqunet-78envs-deimos-lr16-no-guide
  <<: *lux-ssqunet-78envs-deimos-lr2-no-guide
  hyperparam_transitions_kwargs:
    &lux-ssqunet-78envs-deimos-lr16-no-guide-hparam-transitions
    interpolate_method: cosine
    phases:
      - learning_rate: !!float 1e-6
        ent_coef: 0.001
      - learning_rate: !!float 1.6e-4
        ent_coef: 0.001
      - learning_rate: !!float 1e-6
        ent_coef: 0.0001
    durations:
      - 0
      - 0.1
      - 0.55
      - 0.3
      - 0.05

LuxAI_S2-v0-sSqunet-78env-deimos-lr8-adv-norm:
  &lux-ssqunet-78envs-deimos-lr8-adv-norm
  <<: *lux-ssqunet-78envs-deimos-lr4-adv-norm
  hyperparam_transitions_kwargs:
    &lux-ssqunet-78envs-deimos-lr8-hparam-transitions
    interpolate_method: cosine
    phases:
      - learning_rate: !!float 1e-6
        ent_coef: 0.001
      - learning_rate: !!float 8e-5
        ent_coef: 0.001
      - learning_rate: !!float 1e-6
        ent_coef: 0.0001
    durations:
      - 0
      - 0.1
      - 0.55
      - 0.3
      - 0.05

LuxAI_S2-v0-sSqunet-78env-deimos-lr16-adv-norm:
  &lux-ssqunet-78envs-deimos-lr16-adv-norm
  <<: *lux-ssqunet-78envs-deimos-lr4-adv-norm
  hyperparam_transitions_kwargs:
    <<: *lux-ssqunet-78envs-deimos-lr16-no-guide-hparam-transitions

LuxAI_S2-v0-sSqunet-78env-deimos-lr16-slow-start:
  &lux-ssqunet-78envs-deimos-lr16-slow-start
  <<: *lux-ssqunet-78envs-deimos-lr16-adv-norm
  hyperparam_transitions_kwargs:
    interpolate_method: cosine
    phases:
      - learning_rate: !!float 1e-6
        ent_coef: 0.001
      - learning_rate: !!float 1.6e-4
        ent_coef: 0.001
      - learning_rate: !!float 1e-6
        ent_coef: 0.0001
    durations:
      - 0
      - 0.2
      - 0.5
      - 0.25
      - 0.05

LuxAI_S2-v0-sSqunet-78env-deimos-lr16-100m: &lux-ssqunet-78envs-deimos-lr16-100m
  <<: *lux-ssqunet-78envs-deimos-lr16-slow-start
  n_timesteps: !!float 100e6

LuxAI_S2-v0-sSqunet-78env-deimos-push-bots: &lux-ssqunet-78envs-deimos-push-bots
  <<: *lux-ssqunet-78envs-deimos-lr16-100m
  algo_hyperparams: &lux-ssqunet-78envs-deimos-push-bots-algo
    <<: *lux-ssqunet-78envs-deimos-lr1-adv-norm-algo
    multi_reward_weights:
      - 0.3
      - 0.6
      - 0.1

LuxAI_S2-v0-sSqunet-78env-deimos-lr32-100m: &lux-ssqunet-78envs-deimos-lr32-100m
  <<: *lux-ssqunet-78envs-deimos-lr16-100m
  hyperparam_transitions_kwargs:
    &lux-ssqunet-78envs-deimos-lr32-hparam-transitions
    interpolate_method: cosine
    phases:
      - learning_rate: !!float 1e-6
        ent_coef: 0.001
      - learning_rate: !!float 3.2e-4
        ent_coef: 0.001
      - learning_rate: !!float 1e-6
        ent_coef: 0.0001
    durations:
      - 0
      - 0.1
      - 0.55
      - 0.3
      - 0.05

LuxAI_S2-v0-sSqunet-78env-deimos-bots-lr8: &lux-ssqunet-78envs-deimos-bots-lr8
  <<: *lux-ssqunet-78envs-deimos-lr8-adv-norm
  algo_hyperparams: &lux-ssqunet-78envs-deimos-bots-lr8-algo
    <<: *lux-ssqunet-78envs-deimos-push-bots-algo

LuxAI_S2-v0-sSqunet-78env-deimos-Hbots-lr8: &lux-ssqunet-78envs-deimos-hbots-lr8
  <<: *lux-ssqunet-78envs-deimos-bots-lr8
  algo_hyperparams: &lux-ssqunet-78envs-deimos-hbots-lr8-algo
    <<: *lux-ssqunet-78envs-deimos-bots-lr8-algo
    multi_reward_weights:
      - 0.45
      - 0.45
      - 0.1

LuxAI_S2-v0-sSqunet-78env-deimos-lr4-100m: &lux-ssqunet-78env-deimos-lr4-100m
  <<: *lux-ssqunet-78envs-deimos-lr4-adv-norm
  n_timesteps: !!float 100e6

LuxAI_S2-v0-sSqunet-78env-deimos-lr2-100M: &lux-ssqunet-78env-deimos-lr2-100m
  <<: *lux-ssqunet-78envs-deimos-lr2-adv-norm
  n_timesteps: !!float 100e6

LuxAI_S2-v0-sSqunet-78env-deimos-lr1-100M: &lux-ssqunet-78env-deimos-lr1-100m
  <<: *lux-ssqunet-78envs-deimos-lr1-adv-norm
  n_timesteps: !!float 100e6

LuxAI_S2-v0-sSqunet-78env-deimos-lr4-slow-start:
  &lux-ssqunet-78envs-deimos-lr4-slow-start
  <<: *lux-ssqunet-78envs-deimos-lr4-adv-norm
  hyperparam_transitions_kwargs:
    interpolate_method: cosine
    phases:
      - learning_rate: !!float 1e-6
        ent_coef: 0.001
      - learning_rate: !!float 4e-5
        ent_coef: 0.001
      - learning_rate: !!float 1e-6
        ent_coef: 0.0001
    durations:
      - 0
      - 0.2
      - 0.45
      - 0.3
      - 0.05

LuxAI_S2-v0-sSqunet-78env-deimos-lr4-hbots: &lux-ssqunet-78envs-deimos-lr4-hbots
  <<: *lux-ssqunet-78envs-deimos-lr4-adv-norm
  algo_hyperparams:
    <<: *lux-ssqunet-78envs-deimos-hbots-lr8-algo

LuxAI_S2-v0-sSqunet-78env-deimos-lr4-hbots-100m:
  &lux-ssqunet-78envs-deimos-lr4-hbots-100m
  <<: *lux-ssqunet-78envs-deimos-lr4-hbots
  n_timesteps: !!float 100e6

LuxAI_S2-v0-sSqunet-78env-deimos-lr2-hbots-100m:
  &lux-ssqunet-78envs-deimos-lr2-hbots-100m
  <<: *lux-ssqunet-78env-deimos-lr2-100m
  algo_hyperparams:
    <<: *lux-ssqunet-78envs-deimos-hbots-lr8-algo

LuxAI_S2-v0-sSqunet-78env-deimos-lr4d-hbots-100m:
  &lux-ssqunet-78envs-deimos-lr4d-hbots-100m
  <<: *lux-ssqunet-78envs-deimos-lr4-hbots-100m
  hyperparam_transitions_kwargs:
    interpolate_method: cosine
    phases:
      - learning_rate: !!float 1e-6
        ent_coef: 0.001
      - learning_rate: !!float 4e-5
        ent_coef: 0.001
      - learning_rate: !!float 1e-6
        ent_coef: 0.0001
    durations:
      - 0
      - 0.2
      - 0.25
      - 0.5
      - 0.05

LuxAI_S2-v0-sSqnet-78env32-deimos-lr4d-hbots-50m:
  &lux-ssqnet-78env32-deimos-lr4d-hbots-50m
  <<: *lux-ssqunet-78envs-deimos-lr4d-hbots-100m
  n_timesteps: !!float 50e6
  env_hyperparams: &lux-ssqnet-78env32-env
    <<: *lux-ssqunet-78envs-deimos-lr2-no-guide-env
    make_kwargs: &lux-ssqnet-78env32-env-make-kwargs
      <<: *lux-ssqunet-78envs-deimos-lr2-no-guide-env-make-kwargs
      map_size: 32
      MIN_FACTORIES: 2
      MAX_FACTORIES: 3
  eval_hyperparams: &lux-ssqnet-78env32-eval
    <<: *lux-ssqunet-78envs-deimos-lr2-no-guide-eval
    env_overrides: &lux-ssqnet-78env32-eval-env-overrides
      <<: *lux-ssqunet-78envs-deimos-lr2-no-guide-eval-env-overrides
      make_kwargs: &lux-ssqnet-78env32-eval-env-override-make-kwargs
        <<: *lux-ssqunet-78envs-deimos-lr2-no-guide-eval-env-make-kwargs
        map_size: 32
        MIN_FACTORIES: 2
        MAX_FACTORIES: 3
    only_record_video_on_best: false
  algo_hyperparams: &lux-ssqnet-78env32-deimos-lr4d-hbots-50m-algo
    <<: *lux-ssqunet-78envs-deimos-hbots-lr8-algo
    num_minibatches: 3

LuxAI_S2-v0-sSqnet-78env16-deimos-lr4d-hbots-50m:
  &lux-ssqnet-78env16-deimos-lr4d-hbots-50m
  <<: *lux-ssqunet-78envs-deimos-lr4d-hbots-100m
  n_timesteps: !!float 50e6
  env_hyperparams: &lux-ssqnet-78env16-env
    <<: *lux-ssqnet-78env32-env
    make_kwargs: &lux-ssqnet-78env16-env-make-kwargs
      <<: *lux-ssqnet-78env32-env-make-kwargs
      map_size: 16
      MIN_FACTORIES: 1
      MAX_FACTORIES: 2
  eval_hyperparams: &lux-ssqnet-78env16-eval
    <<: *lux-ssqnet-78env32-eval
    env_overrides: &lux-ssqnet-78env16-eval-env-overrides
      <<: *lux-ssqnet-78env32-eval-env-overrides
      make_kwargs: &lux-ssqnet-78env16-eval-env-override-make-kwargs
        <<: *lux-ssqnet-78env32-eval-env-override-make-kwargs
        map_size: 16
        MIN_FACTORIES: 1
        MAX_FACTORIES: 2
  rollout_hyperparams:
    <<: *lux-ssqunet-78envs-deimos-lr2-no-guide-rollout
    n_steps: 96
  algo_hyperparams: &lux-ssqnet-78env16-deimos-lr4d-hbots-50m-algo
    <<: *lux-ssqnet-78env32-deimos-lr4d-hbots-50m-algo
    num_minibatches: 1

LuxAI_S2-v0-sSqnet-78env16-deimos-lr4d-hbots-200m:
  &lux-ssqnet-78env16-deimos-lr4d-hbots-200m
  <<: *lux-ssqnet-78env16-deimos-lr4d-hbots-50m
  n_timesteps: !!float 200e6

LuxAI_S2-v0-sSqnet-78env32-deimos-lr4d-hbots-200m:
  &lux-ssqnet-78env32-deimos-lr4d-hbots-200m
  <<: *lux-ssqnet-78env32-deimos-lr4d-hbots-50m
  n_timesteps: !!float 200e6

LuxAI_S2-v0-debug:
  <<: *lux-ssqunet-78envs-deimos-hbots-lr8
  n_timesteps: !!float 1e6
  device: mps
  env_hyperparams:
    <<: *lux-ssqunet-78envs-deimos-lr2-no-guide-env
    make_kwargs:
      <<: *lux-ssqunet-78envs-deimos-lr2-no-guide-env-make-kwargs
      verbose: 3
      verify: true
    vec_env_class: sync
  eval_hyperparams:
    <<: *lux-ssqunet-78envs-deimos-lr2-no-guide-eval
    env_overrides:
      <<: *lux-ssqunet-78envs-deimos-lr2-no-guide-eval-env-overrides
      make_kwargs:
        <<: *lux-ssqunet-78envs-deimos-lr2-no-guide-eval-env-make-kwargs
        verbose: 3
        verify: true
      vec_env_class: sync
