LuxAI_S2-v0-squnet-iDeimos: &lux-squnet-ideimos
  env_id: LuxAI_S2-v0
  n_timesteps: !!float 40e6
  additional_keys_to_log: ["results", "stats"]
  env_hyperparams: &lux-squnet-ideimos-env
    env_type: lux
    vec_env_class: replay
    n_envs: 24
    make_kwargs: &lux-squnet-ideimos-env-make-defaults
      replay_dirs:
        - replay_dir: data/lux/lux-replays-deimos-npz
          team_name: Deimos
      reward_weights:
        score_vs_opponent: 1
      offset_env_starts: true
      is_npz_dir: true
      factory_ice_distance_buffer: null
    additional_win_loss_reward: true
  rollout_type: reference
  rollout_hyperparams: &lux-squnet-ideimos-rollout
    n_steps: 512
    full_batch_off_accelerator: true
    include_logp: false
    gamma: [0.9997, 0.9997]
    gae_lambda: [0.99, 0.99]
  checkpoints_kwargs:
    history_size: 32
  eval_hyperparams: &lux-eval-defaults
    deterministic: false
    step_freq: !!float 5e6
    skip_evaluate_at_start: true
    score_function: mean
    only_record_video_on_best: true
    score_threshold: 0.37
    env_overrides: &lux-eval-env-overrides
      vec_env_class: sync
      n_envs: 64
      make_kwargs: &lux-eval-env-override-make-kwargs
        reward_weights:
          win_loss: 1
        factory_ice_distance_buffer: null
      additional_win_loss_reward: false
      score_reward_kwargs: null
      play_checkpoints_kwargs:
        n_envs_against_checkpoints: null
  policy_hyperparams: &lux-squnet-ideimos-policy
    actor_head_style: squeeze_unet
    subaction_mask:
      1:
        2: 0
        3: 1
        4: 1
        5: 2
    channels_per_level: [128, 128, 128]
    strides_per_level: [4, 4]
    deconv_strides_per_level: [[2, 2], [2, 2]]
    encoder_residual_blocks_per_level: [3, 2, 4]
    decoder_residual_blocks_per_level: [2, 3]
    additional_critic_activation_functions: [tanh]
    output_activation_fn: tanh
  algo_hyperparams: &lux-squnet-ideimos-algo
    learning_rate: !!float 1e-3
    batch_size: 384
    n_epochs: 2
    vf_coef: [0.25, 0.25]
    max_grad_norm: 0.5
    gradient_accumulation: true
    scale_loss_by_num_actions: true
  hyperparam_transitions_kwargs:
    durations: [0, 1, 0]
    phases:
      - learning_rate: !!float 1e-3
      - learning_rate: 0

LuxAI_S2-v0-squnet-flg: &lux-squnet-flg
  <<: *lux-squnet-ideimos
  env_hyperparams:
    <<: *lux-squnet-ideimos-env
    make_kwargs:
      <<: *lux-squnet-ideimos-env-make-defaults
      replay_dirs:
        - replay_dir: data/lux/lux-replays-flg-npz
          team_name: flg

LuxAI_S2-v0-squnet-ry-andy: &lux-squnet-ry-andy
  <<: *lux-squnet-ideimos
  env_hyperparams:
    <<: *lux-squnet-ideimos-env
    make_kwargs:
      <<: *lux-squnet-ideimos-env-make-defaults
      replay_dirs:
        - replay_dir: data/lux/lux-replays-ry_andy_-npz
          team_name: ry_andy_

LuxAI_S2-v0-squnet-Tigga: &lux-squnet-tigga
  <<: *lux-squnet-ideimos
  env_hyperparams:
    <<: *lux-squnet-ideimos-env
    make_kwargs:
      <<: *lux-squnet-ideimos-env-make-defaults
      replay_dirs:
        - replay_dir: data/lux/lux-replays-tigga-npz
          team_name: Tigga

LuxAI_S2-v0-squnet-SiestaGuru: &lux-squnet-siestaguru
  <<: *lux-squnet-ideimos
  env_hyperparams:
    <<: *lux-squnet-ideimos-env
    make_kwargs:
      <<: *lux-squnet-ideimos-env-make-defaults
      replay_dirs:
        - replay_dir: data/lux/lux-replays-siestaguru-npz
          team_name: SiestaGuru

LuxAI_S2-v0-split-squnet-Deimos: &lux-split-squnet-deimos
  <<: *lux-squnet-ideimos
  policy_hyperparams: &lux-split-squnet-deimos-policy
    <<: *lux-squnet-ideimos-policy
    critic_shares_backbone: false

LuxAI_S2-v0-split-squnet-multi: &lux-split-squnet-multi
  <<: *lux-split-squnet-deimos
  env_hyperparams: &lux-split-squnet-multi-env
    <<: *lux-squnet-ideimos-env
    make_kwargs: &lux-split-squnet-multi-env-make-kwargs
      <<: *lux-squnet-ideimos-env-make-defaults
      replay_dir: null
      team_name: null
      replay_dirs:
        - replay_dir: data/lux/lux-replays-deimos-npz
          team_name: Deimos
        - replay_dir: data/lux/lux-replays-flg-npz
          team_name: flg
        - replay_dir: data/lux/lux-replays-ry_andy_-npz
          team_name: ry_andy_
        - replay_dir: data/lux/lux-replays-tigga-npz
          team_name: Tigga
        - replay_dir: data/lux/lux-replays-siestaguru-npz
          team_name: SiestaGuru

LuxAI_S2-v0-split-short-squnet-multi: &lux-split-short-squnet-multi
  <<: *lux-split-squnet-multi
  policy_hyperparams: &lux-split-short-squnet-multi-policy
    <<: *lux-split-squnet-deimos-policy
    encoder_residual_blocks_per_level: [2, 2, 4]
    decoder_residual_blocks_per_level: [2, 2]

LuxAI_S2-v0-split-short-squnet-acbc-robot: &lux-split-short-squnet-acbc-robot
  <<: *lux-split-short-squnet-multi
  n_timesteps: !!float 50e6
  env_hyperparams: &lux-split-short-squnet-acbc-robot-env
    <<: *lux-split-squnet-multi-env
    make_kwargs: &lux-split-short-squnet-acbc-robot-env-make-kwargs
      <<: *lux-split-squnet-multi-env-make-kwargs
      reward_weights:
        built_light_by_time_remaining: 0.01
        built_heavy_by_time_remaining: 0.1
    score_reward_kwargs:
      episode_end: true
  policy_hyperparams: &lux-split-short-squnet-acbc-robot-policy
    <<: *lux-split-short-squnet-multi-policy
    additional_critic_activation_functions: [tanh, tanh]
    output_activation_fn: identity
    save_critic_separate: true
  rollout_hyperparams:
    <<: *lux-squnet-ideimos-rollout
    gamma: [0.9997, 0.9997, 0.9997]
    gae_lambda: [0.95, 0.95, 0.95]
  algo_hyperparams:
    <<: *lux-squnet-ideimos-algo
    n_epochs: 1
    vf_coef: [0.33, 0.33, 0.33]

LuxAI_S2-v0-short-squnet-rl-robot: &lux-short-squnet-rl-robot
  <<: *lux-split-short-squnet-acbc-robot
  policy_hyperparams:
    <<: *lux-split-short-squnet-acbc-robot-policy
    save_critic_separate: false
    critic_shares_backbone: true
  env_hyperparams: &lux-short-squnet-rl-robot-env
    <<: *lux-split-short-squnet-acbc-robot-env
    make_kwargs: &lux-short-squnet-rl-robot-env-make-kwargs
      <<: *lux-split-short-squnet-acbc-robot-env-make-kwargs
      replay_dirs:
        - replay_dir: data/lux/lux-replays-deimos-npz
          team_name: Deimos
        - replay_dir: data/lux/lux-replays-flg-npz
          team_name: flg

LuxAI_S2-v0-short-squnet-deimos: &lux-short-squnet-deimos
  <<: *lux-short-squnet-rl-robot
  env_hyperparams:
    <<: *lux-short-squnet-rl-robot-env
    make_kwargs:
      <<: *lux-short-squnet-rl-robot-env-make-kwargs
      replay_dirs:
        - replay_dir: data/lux/lux-replays-deimos-npz
          team_name: Deimos

LuxAI_S2-v0-short-squnet-multi: &lux-short-squnet-multi
  <<: *lux-short-squnet-rl-robot
  env_hyperparams:
    <<: *lux-short-squnet-rl-robot-env
    make_kwargs:
      <<: *lux-short-squnet-rl-robot-env-make-kwargs
      replay_dirs:
        - replay_dir: data/lux/lux-replays-deimos-npz
          team_name: Deimos
        - replay_dir: data/lux/lux-replays-flg-npz
          team_name: flg
        - replay_dir: data/lux/lux-replays-ry_andy_-npz
          team_name: ry_andy_
        - replay_dir: data/lux/lux-replays-tigga-npz
          team_name: Tigga
        - replay_dir: data/lux/lux-replays-siestaguru-npz
          team_name: SiestaGuru

LuxAI_S2-v0-debug:
  <<: *lux-short-squnet-multi
  device: mps
  # eval_hyperparams:
  #   <<: *lux-eval-defaults
  #   skip_evaluate_at_start: false
