LuxAI_S2-v0-j1024env16-80m-ent5-lr3c-mgn2-2o3m4h-nga-async-a100:
  &lux-j1024env16-80m-ent5-lr3c-mgn2-2o3m4h-nga-async-a100
  additional_keys_to_log:
    - results
    - stats
    - relative_stats
  algo_hyperparams:
    &lux-j1024env16-80m-ent5-lr3c-mgn2-2o3m4h-nga-async-a100-algo
    autocast_loss: true
    batch_size: 2048
    clip_range: 0.1
    clip_range_vf: null
    ent_coef: 0.005
    gradient_accumulation: false
    learning_rate: 0.0003
    max_grad_norm: 2.0
    multi_reward_weights:
      - 1
      - 0.1
      - 0.2
      - 0.1
      - 0.2
      - 0
      - 0.1
      - 0.2
      - 0.1
      - 0
      - 0.1
      - 0
      - 0
      - 0
    normalize_advantage: true
    normalize_advantages_after_scaling: false
    ppo2_vf_coef_halving: true
    standardize_advantage: false
    teacher_kl_loss_coef: null
    vf_coef: 0.24
    vf_loss_fn: huber_loss
    vf_weights:
      - 1
      - 0.5
      - 0.5
      - 0.5
      - 0.5
      - 0.5
      - 0.5
      - 0.5
      - 0.5
      - 0.5
      - 0.5
      - 0.5
      - 0.5
      - 0.5
  checkpoints_kwargs:
    history_size: 4
  device_hyperparams:
    set_float32_matmul_precision: high
    use_deterministic_algorithms: false
  env_hyperparams: &lux-j1024env16-env
    additional_win_loss_reward: false
    additional_win_loss_smoothing_factor: none
    env_type: lux
    info_rewards:
      episode_end: false
      info_paths:
        - - delta_stats
          - generation
          - ice
        - - delta_stats
          - generation
          - ore
        - - delta_stats
          - generation
          - water
        - - delta_stats
          - generation
          - metal
        - - delta_stats
          - generation
          - power
        - - delta_stats
          - generation
          - light_bots
        - - delta_stats
          - generation
          - heavy_bots
        - - delta_stats
          - generation
          - opponent_kills
        - - delta_stats
          - resources
          - lichen
        - - delta_stats
          - resources
          - factories
        - - delta_stats
          - real_env_steps
        - - delta_stats
          - resources
          - opponent_lichen
        - - delta_stats
          - resources
          - opponent_factories
    make_kwargs: &lux-j1024env16-env-make-kwargs
      MAX_FACTORIES: 2
      MAX_GLOBAL_ID: 256
      MAX_N_UNITS: 128
      MIN_FACTORIES: 1
      USES_COMPACT_SPAWNS_MASK: true
      bid_std_dev: 0
      disable_cargo_pickup: true
      disable_unit_to_unit_transfers: true
      enable_factory_to_digger_power_transfers: true
      enable_light_water_pickup: true
      factory_ice_distance_buffer: 0
      factory_ore_distance_buffer: 0
      init_water_constant: true
      map_size: 16
      min_ice: 2
      min_ore: 2
      relative_stats_eps:
        generation:
          heavy_bots: 0.22
          ice: 22
          light_bots: 0.22
          metal: 11
          opponent_kills: 0.22
          ore: 22
          water: 11
        resources:
          heavy_bots: 0.22
          lichen: 0.22
          light_bots: 0.22
          water_in_factories: 0.22
      reward_weights:
        win_loss: 1
      use_difference_ratio: true
      use_simplified_spaces: true
      valid_spawns_mask_ore_ice_union: true
    n_envs: 1024
    normalize: true
    normalize_kwargs:
      clip_reward: 1
      emv_window_size: 5000000.0
      exponential_moving_mean_var_reward: true
      gamma_reward: 1
      norm_obs: false
      norm_reward: true
    play_checkpoints_kwargs:
      n_envs_against_checkpoints: 256
    score_reward_kwargs: null
    self_play_kwargs: null
    vec_env_class: jux
  env_id: LuxAI_S2-v0
  eval_hyperparams: &lux-j1024env16-eval
    deterministic: false
    env_overrides: &lux-j1024env16-eval-env-overrides
      info_rewards: null
      make_kwargs: &lux-j1024env16-eval-env-overrides-make-kwargs
        MAX_FACTORIES: 2
        MAX_GLOBAL_ID: 256
        MAX_N_UNITS: 128
        MIN_FACTORIES: 1
        USES_COMPACT_SPAWNS_MASK: true
        bid_std_dev: 0
        disable_cargo_pickup: true
        disable_unit_to_unit_transfers: true
        enable_factory_to_digger_power_transfers: true
        enable_light_water_pickup: true
        factory_ice_distance_buffer: 0
        factory_ore_distance_buffer: 0
        init_water_constant: true
        map_size: 16
        min_ice: 2
        min_ore: 2
        reward_weights:
          win_loss: 1
        use_difference_ratio: true
        use_simplified_spaces: true
        valid_spawns_mask_ore_ice_union: true
      n_envs: 128
      play_checkpoints_kwargs:
        n_envs_against_checkpoints: null
    only_checkpoint_best_policies: true
    only_record_video_on_best: false
    score_function: mean
    score_threshold: 0.14
    step_freq: 2500000.0
  hyperparam_transitions_kwargs: null
  lr_by_kl_kwargs: null
  n_timesteps: 80000000.0
  policy_hyperparams:
    &lux-j1024env16-80m-ent5-lr2c-mgn2-2o3m4h-nga-async-a100-policy
    actor_head_style: squeeze_unet
    additional_critic_activation_functions:
      - identity
      - identity
      - identity
      - identity
      - identity
      - identity
      - identity
      - identity
      - identity
      - identity
      - identity
      - identity
      - identity
    channels_per_level:
      - 128
      - 128
      - 128
    critic_channels: 128
    critic_shares_backbone: true
    decoder_residual_blocks_per_level:
      - 2
      - 3
    deconv_strides_per_level:
      - - 2
        - 2
      - - 2
        - 2
    encoder_residual_blocks_per_level:
      - 3
      - 2
      - 2
    load_path: null
    load_run_path: null
    load_run_path_best: true
    normalization: layer
    output_activation_fn: identity
    save_critic_separate: false
    shared_critic_head: true
    strides_per_level:
      - 4
      - 4
    subaction_mask:
      1:
        2: 0
        3: 1
        4: 1
        5: 2
  process_mode: async
  rollout_hyperparams:
    full_batch_off_accelerator: true
    gae_lambda: 0.95
    gamma: 1.0
    n_steps: 32
    num_envs_reset_every_rollout: 0
    prepare_steps: 1024
    random_num_envs_reset_every_rollout: 4
    rolling_num_envs_reset_every_prepare_step: 32
    rolling_num_envs_reset_every_rollout: 0
  rollout_type: sync
  worker_hyperparams:
    n_rollout_workers: 4

LuxAI_S2-v0-j1024env16-80m-ent5-lr2c-mgn2-2o3m4h-nga-async-a100:
  &lux-j1024env16-80m-ent5-lr2c-mgn2-2o3m4h-nga-async-a100
  <<: *lux-j1024env16-80m-ent5-lr3c-mgn2-2o3m4h-nga-async-a100
  algo_hyperparams:
    &lux-j1024env16-80m-ent5-lr2c-mgn2-2o3m4h-nga-async-a100-algo
    <<: *lux-j1024env16-80m-ent5-lr3c-mgn2-2o3m4h-nga-async-a100-algo
    learning_rate: 0.0002

LuxAI_S2-v0-j1024env16-200m-ent5-lr2c-mgn2-2o3m4h-nga-async-a100:
  &lux-j1024env16-200m-ent5-lr2c-mgn2-2o3m4h-nga-async-a100
  <<: *lux-j1024env16-80m-ent5-lr2c-mgn2-2o3m4h-nga-async-a100
  n_timesteps: !!float 200e6

LuxAI_S2-v0-j1024env32-80m-ent5-lr03-mgn4-2omh1lc-ga2-tkl5c-a100:
  &lux-j1024env32-80m-ent5-lr03-mgn4-2omh1lc-ga2-tkl5c-a100
  <<: *lux-j1024env16-80m-ent5-lr3c-mgn2-2o3m4h-nga-async-a100
  algo_hyperparams:
    &lux-j1024env32-80m-ent5-lr03-mgn4-2omh1lc-ga2-tkl5c-a100-algo
    <<: *lux-j1024env16-80m-ent5-lr3c-mgn2-2o3m4h-nga-async-a100-algo
    learning_rate: !!float 5e-5
    teacher_kl_loss_coef: !!float 5e-3
    teacher_loss_batch_size: 8192
    batch_size: 512
    gradient_accumulation: 2
  env_hyperparams: &lux-j1024env32-env
    <<: *lux-j1024env16-env
    make_kwargs: &lux-j1024env32-env-make-kwargs
      <<: *lux-j1024env16-env-make-kwargs
      map_size: 32
      MAX_FACTORIES: 3
      MIN_FACTORIES: 2
      USES_COMPACT_SPAWNS_MASK: false
  eval_hyperparams: &lux-j1024env32-eval
    <<: *lux-j1024env16-eval
    env_overrides: &lux-j1024env32-eval-env-overrides
      <<: *lux-j1024env16-eval-env-overrides
      make_kwargs: &lux-j1024env32-eval-env-overrides-make-kwargs
        <<: *lux-j1024env16-eval-env-overrides-make-kwargs
        map_size: 32
        MAX_FACTORIES: 3
        MIN_FACTORIES: 2
        USES_COMPACT_SPAWNS_MASK: false
  policy_hyperparams:
    &lux-j1024env32-80m-ent5-lr03-mgn4-2omh1lc-ga2-tkl5c-a100-policy
    <<: *lux-j1024env16-80m-ent5-lr2c-mgn2-2o3m4h-nga-async-a100-policy
    load_run_path: sgoodfriend/rl-algo-impls-lux-nips1/b29t2iyn
    load_run_path_best: true
  hyperparam_transitions_kwargs:
    durations: [0, 1, 0]
    phases:
      - ent_coef: 0.005
      - ent_coef: 0.001
  worker_hyperparams:
    n_rollout_workers: 1

LuxAI_S2-v0-j1024env32-80m-ent5-lr03-mgn4-2omh1lc-nga-tkl5c-a100:
  &lux-j1024env32-80m-ent5-lr03-mgn4-2omh1lc-nga-tkl5c-a100
  <<: *lux-j1024env32-80m-ent5-lr03-mgn4-2omh1lc-ga2-tkl5c-a100
  algo_hyperparams:
    &lux-j1024env32-80m-ent5-lr03-mgn4-2omh1lc-nga-tkl5c-a100-algo
    <<: *lux-j1024env32-80m-ent5-lr03-mgn4-2omh1lc-ga2-tkl5c-a100-algo
    gradient_accumulation: false

LuxAI_S2-v0-debug:
  <<: *lux-j1024env32-80m-ent5-lr03-mgn4-2omh1lc-nga-tkl5c-a100
  n_timesteps: !!float 10e6
  device: mps
  env_hyperparams:
    # <<: *lux-j1024env16-env
    <<: *lux-j1024env32-env
    # <<: *lux-j1024env64-a100-env
    make_kwargs:
      # <<: *lux-j1024env16-env-make-kwargs
      <<: *lux-j1024env32-env-make-kwargs
      # <<: *lux-j1024env64-a100-env-make-kwargs
      verbose: 3
      verify: true
    # vec_env_class: sync
  eval_hyperparams:
    # <<: *lux-j1024env16-eval
    <<: *lux-j1024env32-eval
    # <<: *lux-j1024env64-a100-eval
    env_overrides:
      # <<: *lux-j1024env16-eval-env-overrides
      <<: *lux-j1024env32-eval-env-overrides
      # <<: *lux-j1024env64-a100-eval-env-overrides
      make_kwargs:
        # <<: *lux-j1024env16-eval-env-overrides-make-kwargs
        <<: *lux-j1024env32-eval-env-overrides-make-kwargs
        # <<: *lux-j1024env64-a100-eval-env-overrides-make-kwargs
        verbose: 3
        verify: true
